import test from 'node:test';
import assert from 'node:assert/strict';
import { join } from 'node:path';
import { frontendFixture, until } from './fixtures/frontend.mjs';

test('model panel saves real effort and independent mode, supports native selection, keyboard, drag, search, and themes', { timeout: 120000 }, async t => {
  const fx = await frontendFixture(t, { basePath:'/test-dsh/', modelProfile:{reasoningEfforts:{off:null,low:'low',medium:'medium',high:'high',xhigh:'xhigh'},compat:{supportsReasoningEffort:true}},
    additionalModels:[{id:'second-model',name:'第二模型',reasoningEfforts:{low:'low',high:'high'},compat:{supportsReasoningEffort:true}}] });
  const { page } = fx, base = new URL(page.url());
  const mode = async () => (await page.request.get(new URL('trisoul-x/api/model-mode?session='+fx.sessionId,base).href)).json();
  const trigger = page.getByRole('button',{name:'模型与思考强度',exact:true});
  await trigger.click();
  const panel = page.getByRole('dialog',{name:'模型与思考强度',exact:true}), slider = panel.getByRole('slider',{name:'思考强度'});
  await until(async () => await slider.isEnabled());
  await until(async () => await panel.evaluate(el=>el.getAnimations().every(animation=>animation.playState==='finished')));
  const max = Number(await slider.getAttribute('max'));
  const tickCenters=await panel.locator('.omd-effort-ticks i').evaluateAll(items=>items.map(el=>{const r=el.getBoundingClientRect();return r.x+r.width/2;}));
  await slider.press('End');
  await until(async () => (await mode()).enabled);
  assert.equal((await mode()).selected.reasoningEffort,'xhigh');
  assert.equal(await slider.getAttribute('aria-valuetext'),'Ultracode');
  assert.equal(await panel.getByRole('button',{name:/fast/i}).count(),0);
  assert.equal(await panel.locator('.omd-effort-particle').count(),14);
  assert.equal(await panel.locator('.omd-effort-glow').evaluate(el=>getComputedStyle(el).animationName),'omd-ultra-glow');
  assert.equal(await panel.locator('.omd-effort-thumb').evaluate(el=>getComputedStyle(el).borderRadius),'50%');
  await until(async()=>await panel.locator('.omd-effort-ticks i').first().evaluate(el=>getComputedStyle(el).opacity==='0'));
  const fadedCenters=await panel.locator('.omd-effort-ticks i').evaluateAll(items=>items.map(el=>{const r=el.getBoundingClientRect();return r.x+r.width/2;}));
  assert.ok(fadedCenters.every((center,i)=>Math.abs(center-tickCenters[i])<1),'ticks shrink in place without moving along the slider');
  assert.match(await panel.locator('.omd-effort-ticks i').first().evaluate(el=>getComputedStyle(el).transform),/0\.75/);
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({path:join(fx.root,'model-ultracode-light.png')});
  await slider.press('ArrowLeft');
  await until(async () => (await mode()).mode === 'pro');
  assert.equal(await slider.getAttribute('aria-valuetext'),'Pro');
  assert.equal((await mode()).selected.reasoningEffort,'xhigh');
  assert.match(await panel.locator('.omd-effort-fill').evaluate(el=>getComputedStyle(el).backgroundImage),/linear-gradient/);
  assert.equal(await panel.locator('.omd-effort-glow').evaluate(el=>getComputedStyle(el).opacity),'0.4');
  assert.equal(await panel.locator('.omd-effort-particle').first().evaluate(el=>getComputedStyle(el).animationDuration),'3s');
  assert.equal(await panel.locator('.omd-effort-particle').evaluateAll(items=>items.filter(el=>getComputedStyle(el).display!=='none').length),7);
  assert.equal(await panel.locator('.omd-effort-glow').evaluate(el=>getComputedStyle(el).animationName),'omd-ultra-glow');
  await panel.getByRole('status').getByText('分工实现、持续迭代，可能需要更多时间。',{exact:true}).waitFor();
  await panel.getByRole('button',{name:'界面预览模型',exact:true}).click();
  await panel.getByRole('option',{name:'第二模型'}).click();
  await until(async () => (await mode()).selected.model==='second-model');
  assert.equal((await mode()).mode,'pro');
  assert.equal((await mode()).selected.reasoningEffort,'high');
  await panel.getByRole('button',{name:'第二模型',exact:true}).click();
  await panel.getByRole('option',{name:'界面预览模型'}).click();
  await until(async () => await slider.isVisible() && await slider.isEnabled());
  assert.equal((await mode()).mode,'pro');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
  assert.equal(await panel.locator('.omd-effort-glow').evaluate(el=>getComputedStyle(el).animationName),'none');
  assert.equal(await panel.locator('.omd-effort-particle').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});
  await panel.getByRole('button',{name:'恢复默认思考强度'}).click();
  await until(async () => (await mode()).mode === 'off');
  assert.notEqual((await mode()).selected.reasoningEffort,'xhigh');
  await slider.press('End');
  await until(async () => (await mode()).mode === 'ultracode');
  await slider.press('ArrowLeft');
  await until(async () => (await mode()).mode === 'pro');
  await slider.press('ArrowLeft');
  await until(async () => !(await mode()).enabled);
  assert.equal((await mode()).selected.reasoningEffort,'xhigh','regular highest effort and mode are different stops');
  assert.equal(await panel.locator('.omd-effort-particle').first().evaluate(el=>getComputedStyle(el).opacity),'0');
  await slider.press('End'); await until(async ()=>(await mode()).enabled);
  // Native /model and any other host entry must clear mode even at the same actual effort.
  await fx.rpc('session/selectModel',{sessionId:fx.sessionId,provider:'fixture',model:'fixture',reasoningEffort:'xhigh'});
  await until(async () => await slider.getAttribute('aria-valuetext') === '极高');
  await slider.press('End'); await until(async ()=>(await mode()).enabled);
  await panel.getByRole('button',{name:'恢复默认思考强度'}).click();
  await until(async () => !(await mode()).enabled && (await mode()).selected.reasoningEffort !== 'xhigh');
  const before = await mode(), box = await slider.boundingBox();
  await page.mouse.move(box.x+14,box.y+box.height/2); await page.mouse.down();
  await page.mouse.move(box.x+box.width-14,box.y+box.height/2,{steps:5});
  assert.equal((await mode()).revision,before.revision,'drag preview does not save each intermediate stop');
  assert.equal(await slider.inputValue(),String(max));
  await page.mouse.up(); await until(async () => (await mode()).enabled);
  const touch=await page.context().newCDPSession(page);
  await touch.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
  const stable=await mode(), touchBox=await slider.boundingBox();
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBox.x+touchBox.width-14,y:touchBox.y+22}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchBox.x+14,y:touchBox.y+22}]});
  assert.equal(await slider.inputValue(),'0');
  assert.equal((await mode()).revision,stable.revision);
  await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  assert.equal(await slider.inputValue(),String(max));
  assert.equal((await mode()).revision,stable.revision,'cancelled touch drag does not save');
  await touch.send('Emulation.setTouchEmulationEnabled',{enabled:false}); await touch.detach();
  await page.mouse.move(box.x+14,box.y+box.height/2); await page.mouse.down();
  await page.mouse.move(box.x+box.width-14,box.y+box.height/2);
  await fx.rpc('session/selectModel',{sessionId:fx.sessionId,provider:'fixture',model:'fixture',reasoningEffort:'low'});
  await until(async()=>await trigger.innerText().then(text=>text.includes('低')));
  await page.mouse.up();
  await panel.getByRole('alert').getByText(/模型设置已在另一处更新/).waitFor();
  assert.equal((await mode()).selected.reasoningEffort,'low','an old drag cannot overwrite a newer native selection');
  assert.equal((await mode()).enabled,false);
  await slider.press('End'); await until(async () => (await mode()).enabled);
  await panel.getByRole('button',{name:'界面预览模型',exact:true}).click();
  await panel.getByRole('searchbox',{name:'搜索模型'}).fill('absent');
  await panel.getByText('没有匹配的模型').waitFor();
  await panel.getByRole('searchbox').fill('第二');
  await panel.getByRole('option',{name:'第二模型'}).click();
  await until(async () => (await mode()).selected.model==='second-model');
  assert.equal((await mode()).selected.reasoningEffort,'high'); assert.equal((await mode()).enabled,true);
  await panel.getByRole('button',{name:'第二模型',exact:true}).click();
  await panel.getByRole('searchbox').fill('界面');
  await panel.getByRole('option',{name:'界面预览模型'}).click();
  await until(async () => await slider.isVisible()); assert.equal((await mode()).enabled,true);
  await slider.press('Escape'); await panel.waitFor({state:'hidden'});
  assert.equal(await trigger.evaluate(el => document.activeElement === el),true);
  await page.reload(); await trigger.waitFor();
  await trigger.click(); await until(async () => await slider.getAttribute('aria-valuetext') === 'Ultracode');
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
  assert.equal(await panel.locator('.omd-effort-glow').evaluate(el=>getComputedStyle(el).animationName),'none');
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({path:join(fx.root,'model-ultracode-dark.png')});
  await page.setViewportSize({width:375,height:760});
  await until(async () => { const bounds=await panel.boundingBox();return bounds.x>=0&&bounds.x+bounds.width<=375; });
  const send=await page.getByRole('button',{name:'发送消息',exact:true}).boundingBox();
  assert.ok(send.x+send.width<=375,'model controls must leave the send button inside a narrow viewport');
  if (process.env.TRISOUL_UI_ARTIFACTS) { await page.screenshot({path:join(fx.root,'model-ultracode-mobile.png')}); console.log('Model panel artifacts:',fx.root); }
  assert.deepEqual(fx.errors,[]); assert.deepEqual(fx.escapedPaths,[]);
});

test('model panel retains keyboard control after saves and failures, including Escape during a pending save', { timeout: 90000 }, async t => {
  const f = await frontendFixture(t, {
    modelProfile: { reasoningEfforts: { off: null, low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh' }, compat: { supportsReasoningEffort: true } },
    additionalModels: [{ id: 'second-model', name: '第二模型', reasoningEfforts: { low: 'low', high: 'high' }, compat: { supportsReasoningEffort: true } }],
  });
  const { page } = f, trigger = page.getByRole('button', { name: '模型与思考强度', exact: true });
  const panel = page.getByRole('dialog', { name: '模型与思考强度', exact: true });
  const slider = panel.getByRole('slider', { name: '思考强度' });
  let requests = 0, fail = false, hold = false, pending;
  t.after(() => pending?.abort().catch(() => {}));
  await page.route('**/trisoul-x/api/model-mode?*', route => {
    if (route.request().method() !== 'POST') return route.continue();
    requests++;
    const body = route.request().postDataJSON();
    assert.ok(['off','pro','ultracode'].includes(body.mode));
    assert.equal(Object.hasOwn(body,'ultracode'),false);
    if (hold) { pending = route; return; }
    if (fail) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '测试：模型设置暂不可用' }) });
    return route.continue();
  });
  await until(async () => (await trigger.innerText()).includes('界面预览模型'));
  await trigger.click(); await until(async () => await slider.isEnabled());
  await slider.press('End');
  await until(async () => requests === 1 && await panel.getAttribute('aria-busy') === 'false');
  assert.equal(await slider.evaluate(el => el === document.activeElement), true, 'saving must restore the active slider');
  await page.keyboard.press('ArrowLeft');
  await until(async () => requests === 2 && await panel.getAttribute('aria-busy') === 'false');
  assert.equal(await slider.evaluate(el => el === document.activeElement), true);
  fail = true; await page.keyboard.press('ArrowLeft');
  await panel.getByRole('alert').getByText('测试：模型设置暂不可用', { exact: true }).waitFor();
  await until(async () => await slider.evaluate(el => el === document.activeElement));
  await page.keyboard.press('Escape'); await panel.waitFor({ state: 'hidden' });
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true);
  await trigger.click(); await panel.getByRole('button', { name: '界面预览模型', exact: true }).click();
  const second = panel.getByRole('option', { name: '第二模型', exact: true });
  await second.press('Enter');
  await panel.getByRole('alert').getByText('测试：模型设置暂不可用', { exact: true }).waitFor();
  await until(async () => await second.evaluate(el => el === document.activeElement));
  await page.keyboard.press('Escape'); await until(async () => await slider.isVisible());
  hold = true; await slider.press('Home'); await until(() => pending);
  assert.equal(await panel.evaluate(el => el === document.activeElement), true, 'pending save keeps the popup keyboard reachable');
  await page.keyboard.press('Escape'); await panel.waitFor({ state: 'hidden' });
  const late = pending; pending = null;
  await late.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '测试：迟到错误' }) });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await panel.isVisible(), false);
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true, 'late settlement cannot reopen or steal focus');
  hold = false; fail = false;
  await trigger.click(); await until(async () => await slider.isEnabled());
  await panel.getByRole('button', { name: '界面预览模型', exact: true }).click();
  hold = true; await second.press('Enter'); await until(() => pending);
  await page.keyboard.press('Shift+Tab'); await panel.waitFor({ state: 'hidden' });
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true);
  const selection = pending; pending = null; await selection.continue();
  await until(async () => (await trigger.innerText()).includes('第二模型'));
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await panel.isVisible(), false);
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true, 'successful late model selection cannot steal focus after leaving');
  assert.deepEqual(f.errors, []);
});
