import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir, writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {frontendFixture,until} from './fixtures/frontend.mjs';
import {PERSONALITY_PRESETS} from '../src/cc-adaptation/personality.mjs';
const response=content=>({delta:{role:'assistant',content},finish_reason:'stop'});

test('personality and requirement presets coexist across save, reload and first optimization without crossing prompt scopes', {timeout:90000}, async t=>{
  const main=[], optimizations=[];
  const f=await frontendFixture(t,{omdConfig:{identityPrompt:'原来的人格',contextEnabled:false},reply:p=>{main.push(p);return response('已完成组合验收');},optimizerReply:p=>{optimizations.push(p);return response('完成当前任务，保留必要细节，并检查结果。');}});
  const {page}=f, output=process.env.TRISOUL_UI_ARTIFACTS;
  const openSettings=async()=>{
    await page.getByRole('button',{name:'设置',exact:true}).click();
    const panel=page.getByRole('dialog',{name:'设置'});
    await panel.getByRole('button',{name:'Oh My DSH',exact:true}).click();
    await panel.getByRole('button',{name:'模型与身份',exact:true}).click();return panel;
  };
  let panel=await openSettings();
  await panel.getByLabel('人格预设',{exact:true}).selectOption('softie');
  await panel.getByRole('button',{name:'保存设置',exact:true}).click();
  await until(()=>panel.getByRole('button',{name:'保存设置',exact:true}).isDisabled());
  if(output){await mkdir(output,{recursive:true});await panel.screenshot({path:join(output,'OMD-人格预设-软乎乎.png')});}
  await panel.getByRole('button',{name:'推荐插件',exact:true}).click();
  await panel.getByRole('searchbox',{name:'搜索推荐插件'}).fill('OpenDesign');
  const card=panel.locator('.tx-recommended-card');
  await card.waitFor();assert.match(await card.innerText(),/52/);
  assert.equal(await card.getByRole('button',{name:'安装',exact:true}).count(),1);
  assert.equal(await card.getByRole('link',{name:'查看 OpenDesign · DSH 技能桥接 项目（新窗口）',exact:true}).getAttribute('href'),'https://github.com/omegapaopao/dsh-open-design');
  if(output)await panel.screenshot({path:join(output,'OMD-OpenDesign-一键入口.png')});
  await panel.getByRole('button',{name:'Oh My DSH',exact:true}).click();
  await panel.getByRole('button',{name:'模型与身份',exact:true}).click();
  assert.equal(await panel.getByLabel('人格预设',{exact:true}).inputValue(),'softie');
  await page.keyboard.press('Escape');
  const editor=page.locator('[data-composer-input]');await editor.fill('请完成当前任务并检查结果');
  await page.getByRole('button',{name:'展开提示词优化',exact:true}).click();
  const drawer=page.getByRole('dialog',{name:'提示词优化',exact:true});
  const requirements='使用简体中文，先说结论，保留必要细节。';
  await drawer.getByLabel('额外优化要求',{exact:true}).fill(requirements);
  await drawer.getByLabel('要求预设名称',{exact:true}).fill('简洁中文');
  await drawer.getByRole('button',{name:'保存预设',exact:true}).click();
  const selected=await drawer.getByLabel('额外要求预设',{exact:true}).inputValue();assert.ok(selected);
  if(output)await drawer.screenshot({path:join(output,'OMD-首轮额外要求与命名预设.png')});
  await drawer.getByRole('button',{name:'开始优化',exact:true}).click();
  await until(async()=>await editor.innerText()==='完成当前任务，保留必要细节，并检查结果。');
  assert.equal(optimizations.length,1);
  const opt=JSON.stringify(optimizations[0].messages);assert.match(opt,/使用简体中文，先说结论，保留必要细节/);assert.doesNotMatch(opt,/SOFTIE|HARDCORE|小爪子/);
  await page.reload();await page.getByRole('button',{name:'打开工作台',exact:true}).waitFor();
  panel=await openSettings();assert.equal(await panel.getByLabel('人格预设',{exact:true}).inputValue(),'softie');
  assert.equal(await panel.getByLabel('身份提示词',{exact:true}).inputValue(),PERSONALITY_PRESETS.softie.text);
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'展开提示词优化',exact:true}).click();
  assert.equal(await drawer.getByLabel('额外要求预设',{exact:true}).inputValue(),selected);
  assert.equal(await drawer.getByLabel('额外优化要求',{exact:true}).inputValue(),requirements);
  await f.rpc('session/prompt',{requestId:crypto.randomUUID(),sessionId:f.sessionId,mode:'queue',content:[{type:'text',text:'组合验收继续'}]});
  const base=new URL(page.url()).origin;
  await until(async()=> (await (await page.request.get(base+'/trisoul-x/api/state?session='+f.sessionId)).json()).running==='idle');
  const prompt=main.at(-1).messages.filter(x=>x.role==='system').map(x=>x.content).join('\n');
  assert.equal(prompt.split(PERSONALITY_PRESETS.softie.text).length-1,1);assert.doesNotMatch(prompt,/使用简体中文，先说结论，保留必要细节/);
  assert.deepEqual(f.errors,[]);
  if(output)await writeFile(join(output,'combined-request-evidence.json'),JSON.stringify({localFakeProvider:true,optimizerRequirementsReached:opt.includes(requirements),optimizerHasPersonality:false,mainPersonalityCount:1,mainHasOptimizerRequirements:false,pageErrors:f.errors},null,2));
});
