import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { frontendFixture, until } from './fixtures/frontend.mjs';

test('default narrow sidebar overlays readable content and restores pointer and keyboard access', { timeout: 120000 }, async t => {
  const { page, sessionId, errors } = await frontendFixture(t);
  const browser = page.locator('[data-omd-sidebar-browser]');
  const center = page.locator('[data-omd-surface="conversation"]');
  const drawer = page.getByRole('dialog', { name: '侧栏导航', exact: true });
  const expand = page.getByRole('button', { name: '打开侧边栏', exact: true });
  const row = browser.locator(`[data-row-key="session:${sessionId}"]`);
  const open = async () => { await expand.click(); await drawer.waitFor(); };
  const closed = async () => {
    await drawer.waitFor({ state: 'hidden' });
    await until(async () => await browser.getAttribute('data-wide') === 'false');
    assert.equal(await center.evaluate(el => el.inert), false);
  };
  await page.setViewportSize({ width: 390, height: 844 });
  await open();
  assert.ok((await center.boundingBox()).width >= 320, 'the conversation remains readable behind the drawer: ' + JSON.stringify(await center.evaluate(el => ({ width: el.getBoundingClientRect().width, grid: getComputedStyle(el.parentElement).gridTemplateColumns, right: el.parentElement.style.getPropertyValue('--omd-sidebar-right-width') }))));
  assert.ok((await drawer.boundingBox()).width <= 342, 'there is visible space to dismiss the drawer');
  assert.equal(await center.evaluate(el => el.inert), true);
  if (process.env.TRISOUL_UI_ARTIFACTS) {
    await mkdir(process.env.TRISOUL_UI_ARTIFACTS, { recursive: true });
    await page.screenshot({ path: join(process.env.TRISOUL_UI_ARTIFACTS, 'sidebar-mobile-overlay.png') });
  }
  await page.getByRole('button', { name: '收起侧栏', exact: true }).click({ position: { x: 370, y: 400 } });
  await closed();
  await open();
  const settings = drawer.getByRole('button', { name: '设置', exact: true });
  await settings.focus(); await page.keyboard.press('Tab');
  assert.equal(await drawer.evaluate(el => el.contains(document.activeElement)), true);
  assert.equal(await settings.evaluate(el => el === document.activeElement), false);
  await page.keyboard.press('Shift+Tab');
  assert.equal(await settings.evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Escape'); await closed();
  await open();
  const searchButton = page.getByRole('button', { name: '搜索会话', exact: true });
  await searchButton.click();
  await browser.locator('input[type="text"]').first().fill('整理');
  await page.keyboard.press('Escape');
  await until(async () => await searchButton.evaluate(el => el === document.activeElement));
  assert.equal(await drawer.isVisible(), true, 'Escape first closes search and restores its visible trigger');
  await page.keyboard.press('Escape'); await closed();
  await open(); await row.click(); await closed();
  await open(); await row.focus(); await page.keyboard.press('Shift+F10');
  await until(async () => await page.getByRole('menu').evaluate(el => el.contains(document.activeElement)));
  await page.keyboard.press('Escape');
  await until(async () => await page.getByRole('menu').count() === 0);
  assert.equal(await drawer.isVisible(), true, 'the menu consumes the first Escape');
  await until(async () => await row.evaluate(el => el === document.activeElement));
  await page.keyboard.press('Escape'); await closed();
  await open();
  await settings.click();
  const settingsDialog = page.getByRole('dialog', { name: '设置', exact: true });
  await settingsDialog.getByRole('button', { name: '外观', exact: true }).click();
  await page.getByLabel('主题', { exact: true }).selectOption('codex-desktop');
  await drawer.waitFor({ state: 'hidden' });
  assert.equal(await center.evaluate(el => el.inert), false, 'changing layouts releases only the overlay-owned inert state');
  await page.setViewportSize({ width: 1100, height: 760 });
  await page.getByLabel('主题', { exact: true }).selectOption('default');
  await page.keyboard.press('Escape'); await settingsDialog.waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 844 }); await open();
  await page.getByRole('button', { name: '搜索会话', exact: true }).click();
  const focusedSearch = browser.locator('input[type="text"]').first();
  await focusedSearch.fill('仍在编辑');
  await page.setViewportSize({ width: 1100, height: 760 });
  await drawer.waitFor({ state: 'hidden' });
  assert.equal(await center.evaluate(el => el.inert), false);
  assert.equal(await page.locator('[data-omd-sidebar-overlay]').count(), 0);
  assert.equal(await page.getByRole('button', { name: '收起侧栏', exact: true }).isVisible(), false);
  assert.equal(await focusedSearch.evaluate(el => el === document.activeElement), true, 'resizing to a wide view preserves current editing focus');
  assert.deepEqual(errors, []);
});
