import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { frontendFixture, until } from './fixtures/frontend.mjs';
import { validateManifest, versionStatus, parseVersion } from '../src/version.mjs';
const version = JSON.parse(readFileSync(new URL('../package.json', import.meta.url))).version;
const nextVersion = `${parseVersion(version).core[0] + 1n}.0.0`, laterVersion = `${parseVersion(version).core[0] + 2n}.0.0`;
const release = (v, severity = 'normal') => ({ version: v, severity, title: severity === 'required' ? '重要缺陷修复' : '常规功能更新', notes: ['更新说明仅为文本。'] });
const status = rows => ({ ...versionStatus(version, validateManifest({ schema: 1, releases: rows })), checkedAt: Date.now(), error: null, stale: false });

test('update stays inside the version panel, survives reopening, retries failures and reports restart', { timeout: 90000 }, async t => {
  let response = status([release(version)]), state = { phase: 'idle', available: true }, posts = 0;
  const f = await frontendFixture(t, { basePath: '/omd/', versionResponse: () => response }), { page } = f;
  await page.route('**/trisoul-x/api/version-update', async route => {
    if (route.request().method() === 'POST') {
      posts++; assert.deepEqual(route.request().postDataJSON(), { version: nextVersion });
      state = { phase: 'installing', available: false, targetVersion: nextVersion };
    }
    await route.fulfill({ json: state });
  });
  const trigger = page.getByRole('button', { name: '关于 Oh My DSH', exact: true });
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: '关于 Oh My DSH' });
  assert.equal(await dialog.getByRole('button', { name: '更新', exact: true }).count(), 0);
  response = status([release(nextVersion), release(version)]);
  await dialog.getByRole('button', { name: '检查更新', exact: true }).click();
  const install = dialog.getByRole('button', { name: '更新', exact: true });
  await until(() => install.isEnabled());
  assert.equal(await page.locator('.omd-version > button').count(), 1, 'the original info icon is retained');
  assert.equal(await dialog.getByRole('link', { name: '查看新版说明 ↗' }).getAttribute('href'), 'https://github.com/gulagala001/oh-my-dsh/releases/tag/v' + nextVersion);
  await install.click();
  await until(() => dialog.getByRole('button', { name: '更新中…', exact: true }).isDisabled());
  assert.equal(posts, 1);
  await page.keyboard.press('Escape'); await trigger.click();
  await dialog.getByText('正在下载并安装更新…', { exact: true }).waitFor();
  assert.equal(posts, 1, 'reopening observes the existing job');
  state = { phase: 'failed', available: true, targetVersion: nextVersion, error: '下载失败，请重试。' };
  await dialog.getByRole('alert').filter({ hasText: '下载失败' }).waitFor();
  await dialog.getByRole('button', { name: '重试更新', exact: true }).click();
  await until(async () => posts === 2);
  state = { phase: 'restart-required', available: false, targetVersion: nextVersion };
  await dialog.getByText('更新已安装 · 待重启', { exact: true }).waitFor();
  assert.equal(await dialog.getByTestId('omd-current-version').innerText(), version, 'installation does not pretend the running version changed');
  assert.ok((await dialog.innerText()).includes('重启 DSH 服务'));
  assert.equal(await dialog.locator('.omd-version-install').count(), 0);
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.setViewportSize({ width: 390, height: 844 });
  const bounds = await dialog.boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({ path: join(f.root, 'version-update-restart.png') });
  assert.deepEqual(f.errors, []); assert.deepEqual(f.escapedPaths, []);
});

test('macOS desktop brand span keeps version details accessible across sidebar remounts', { timeout: 60000 }, async t => {
  const { page, errors } = await frontendFixture(t);
  // Exercise the host's macOS brand markup without requiring Electron's keyboard bridge.
  // Toggle programmatically because the Web fixture lacks the native titlebar layout.
  await page.evaluate(() => { document.documentElement.dataset.platform = 'darwin'; });
  await page.locator('.hHd-Xa_toggle').evaluate(el => el.click());
  await until(async () => await page.locator('.tx-wordmark').count() === 0);
  await page.locator('.hHd-Xa_toggle').evaluate(el => el.click());
  await page.locator('span.hHd-Xa_brand .tx-wordmark').waitFor();
  const trigger = page.getByRole('button', { name: '关于 Oh My DSH', exact: true });
  await trigger.waitFor();
  assert.equal(await trigger.evaluate(el => el.parentElement.closest('button, [aria-hidden="true"]')), null);
  assert.equal(await page.locator('.omd-version-anchor').count(), 1);
  const word = await page.locator('.tx-wordmark').boundingBox(), hit = await trigger.boundingBox();
  assert.ok(hit.x >= word.x + word.width - 1 && hit.x - word.x - word.width < 25);
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: '关于 Oh My DSH' });
  await dialog.waitFor();
  assert.equal(await dialog.getByTestId('omd-current-version').innerText(), version);
  await page.keyboard.press('Escape');
  await until(async () => !await dialog.isVisible());
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true);
  await page.locator('.hHd-Xa_toggle').evaluate(el => el.click());
  await until(async () => await page.locator('.omd-version-anchor').count() === 0);
  await page.locator('.hHd-Xa_toggle').evaluate(el => el.click());
  await trigger.waitFor();
  assert.equal(await page.locator('.omd-version-anchor').count(), 1);
  await trigger.click(); await dialog.waitFor();
  assert.deepEqual(errors, []);
});

test('brand i opens version details; green/red indicators, offline state, keyboard and collapse all work', { timeout: 90000 }, async t => {
  let response = status([release(version)]), calls = 0;
  const f = await frontendFixture(t, { versionResponse: () => { calls++; return response; } }), { page } = f;
  const trigger = page.getByRole('button', { name: '关于 Oh My DSH', exact: true });
  await trigger.waitFor(); await until(async () => calls > 0 && await trigger.getAttribute('data-update-level') === 'none');
  assert.equal(await page.locator('.omd-version-anchor').count(), 1);
  assert.equal(await trigger.evaluate(el => el.parentElement.closest('button')), null, 'never nest inside the brand/home button');
  const word = await page.locator('.tx-wordmark').boundingBox(), hit = await trigger.boundingBox();
  assert.ok(hit.x >= word.x + word.width - 1 && hit.x - word.x - word.width < 25, 'i stays next to the wordmark');
  assert.ok(Math.abs(hit.y - word.y) < 12);
  const title = await page.title(); await trigger.click();
  const dialog = page.getByRole('dialog', { name: '关于 Oh My DSH' }); await dialog.waitFor();
  assert.equal(await page.title(), title, 'opening information must not navigate home');
  assert.equal(await dialog.getByTestId('omd-current-version').innerText(), version);
  assert.ok((await dialog.innerText()).includes('已是最新版'));
  assert.equal(await trigger.locator('.omd-update-dot').count(), 0);
  await page.keyboard.press('Escape'); await until(async () => !await dialog.isVisible());
  assert.equal(await trigger.evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Enter'); await dialog.waitFor();
  await dialog.evaluate(element => element.dispatchEvent(new Event('close')));
  assert.equal(await dialog.isVisible(), true, 'a queued close event cannot dismiss a newly reopened modal');
  response = status([release(nextVersion), release(version)]);
  await dialog.getByRole('button', { name: '检查更新', exact: true }).click();
  await until(async () => await trigger.getAttribute('data-update-level') === 'normal');
  assert.equal(await trigger.locator('.omd-update-dot').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(34, 197, 94)');
  assert.ok((await dialog.innerText()).includes('普通更新'));
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({ path: join(f.root, 'version-normal.png') });
  response = status([release(laterVersion), release(nextVersion, 'required'), release(version)]);
  await dialog.getByRole('button', { name: '检查更新', exact: true }).click();
  await until(async () => await trigger.getAttribute('data-update-level') === 'required');
  assert.equal(await trigger.locator('.omd-update-dot').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(239, 68, 68)');
  assert.ok((await dialog.innerText()).includes('必要更新'));
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({ path: join(f.root, 'version-required.png') });
  await dialog.getByRole('button', { name: '关闭版本信息' }).click();
  await until(async () => !await dialog.isVisible()); assert.equal(await trigger.getAttribute('data-update-level'), 'required', 'reading a notice does not mark an update as installed');
  await trigger.click(); await dialog.waitFor();
  response = { ...response, stale: true, error: '暂时无法检查更新，请检查网络后重试。' };
  await dialog.getByRole('button', { name: '检查更新', exact: true }).click();
  await dialog.getByRole('alert').waitFor(); assert.equal(await trigger.getAttribute('data-update-level'), 'required');
  assert.ok((await dialog.innerText()).includes('上次检查结果'));
  await page.emulateMedia({ colorScheme: 'dark' });
  if (process.env.TRISOUL_UI_ARTIFACTS) await page.screenshot({ path: join(f.root, 'version-required-dark.png') });
  const screen = page.viewportSize(); await page.mouse.click(screen.width - 12, screen.height - 12); await until(async () => !await dialog.isVisible());
  await page.locator('.hHd-Xa_toggle').click(); await until(async () => await page.locator('.omd-version-anchor').count() === 0);
  await page.locator('.hHd-Xa_toggle').click(); await trigger.waitFor();
  assert.equal(await page.locator('.omd-version-anchor').count(), 1, 'expand/collapse does not duplicate listeners or buttons');
  response = { currentVersion: version, latestVersion: null, status: 'unknown', severity: 'none', releases: [], checkedAt: null, error: '暂时无法检查更新，请检查网络后重试。' };
  await trigger.click(); await dialog.waitFor(); await dialog.getByRole('button', { name: '检查更新', exact: true }).click();
  await until(async () => (await dialog.innerText()).includes('尚未确认最新版本'));
  assert.equal(await trigger.locator('.omd-update-dot').count(), 0);
  const bounds = await dialog.boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= screen.width);
  await page.keyboard.press('Escape'); await until(async () => !await dialog.isVisible());
  assert.equal(await page.locator('.omd-version-dialog [role=alert]').count(), 0, 'closed information must not publish hidden global error alerts');
  assert.deepEqual(f.errors, []);
  if (process.env.TRISOUL_UI_ARTIFACTS) console.log('Version UI artifacts:', f.root);
});
