#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, lstatSync, realpathSync, rmSync, renameSync } from 'node:fs';
import { resolve, join, dirname, relative, isAbsolute } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const BUNDLE = dirname(fileURLToPath(import.meta.url));
const META = JSON.parse(readFileSync(join(BUNDLE, 'migration.json'), 'utf8'));
const sha256 = value => createHash('sha256').update(value).digest('hex');
const gitBlob = value => createHash('sha1').update('blob ' + Buffer.byteLength(value) + '\0').update(value).digest('hex');
const read = path => readFileSync(path, 'utf8');
function once(text, before, after, label) {
  if (text.split(before).length !== 2) throw new Error('Expected exactly one source anchor: ' + label);
  return text.replace(before, () => after);
}
export function buildEdits(originals, wrapper) {
  const edits = new Map();
  const pkg = JSON.parse(originals['package.json']);
  for (const kind of ['dependencies', 'devDependencies', 'peerDependencies']) {
    for (const name of Object.keys(pkg[kind] || {})) {
      if (name === '@deepseek-ai/dsh' || name.startsWith('@deepseek-ai/dsh-')) pkg[kind][name] = META.dsh;
    }
  }
  // Lockfile is regenerated by --install, never fabricated or silently ignored.
  edits.set('package.json', JSON.stringify(pkg, null, 2) + '\n');
  let preset = originals['presets/trisoul-x/agent.cordis.yml'];
  preset = once(preset, "name: '@deepseek-ai/dsh-workflow-worker-thread'", "name: '@deepseek-ai/dsh-workflow-ptc'", 'workflow engine');
  preset = once(preset, 'id: workflow-worker-thread', 'id: workflow-ptc', 'workflow row');
  const start = preset.indexOf('        section: |\n'), stop = preset.indexOf('\n- id: compaction', start);
  if (start < 0 || stop < 0) throw new Error('Plan-mode config anchors are missing.');
  const plan = read(join(BUNDLE, 'prompts/runtime/plan-mode.md')).trim().split('\n').map(l => '              ' + l).join('\n');
  preset = preset.slice(0, start) + '        section: |\n' + plan + '\n' + preset.slice(stop);
  edits.set('presets/trisoul-x/agent.cordis.yml', preset);
  edits.set('src/index.mjs', once(originals['src/index.mjs'], "ctx.on('agent/session-start'", "ctx.on('agent/created'", 'created listener'));
  let agent = originals['src/dsh-agent.mjs'];
  if (agent.includes('installPromptAdapter')) throw new Error('An adapter is already installed; do not stack versions.');
  agent = "import { installPromptAdapter } from './cc-adaptation/cc-prompt-adapter.mjs';\n" + agent;
  agent = once(agent, '  const hub = ctx.trisoulX;', '  const hub = ctx.trisoulX;\n  installPromptAdapter(ctx);', 'main-agent installer');
  edits.set('src/dsh-agent.mjs', agent);
  const state = originals['src/state-zone.mjs'];
  if (gitBlob(state) !== wrapper.base_git_blob) throw new Error('State-zone source is not the audited version.');
  edits.set('src/state-zone.mjs', once(state, wrapper.old_line, wrapper.new_line, 'state wrapper'));
  return edits;
}
function run(bin, args, cwd, stdio = 'pipe') {
  // Never invoke a shell with interpolated user paths.
  if (process.platform === 'win32' && bin === 'pnpm.cmd') {
    if (args.some(a => !/^[A-Za-z0-9_.=-]+$/.test(a))) throw new Error('Unsupported command argument');
    return execFileSync(process.env.ComSpec || 'cmd.exe', ['/d','/s','/c', 'pnpm ' + args.join(' ')], { cwd, encoding:'utf8', stdio, maxBuffer:64*1024*1024 });
  }
  return execFileSync(bin, args, { cwd, encoding: 'utf8', stdio, maxBuffer: 64 * 1024 * 1024 });
}
function atomic(path, bytes) {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = path + '.tri-' + randomUUID();
  writeFileSync(tmp, bytes, { mode: 0o600 });
  renameSync(tmp, path);
}
function assertOwnedPath(project, name) {
  const dest = resolve(project, name), rel = relative(project, dest);
  if (rel.startsWith('..') || isAbsolute(rel)) throw new Error('Unsafe path: ' + name);
  let part = project;
  for (const bit of rel.split(/[\\/]/)) {
    part = join(part, bit);
    if (existsSync(part) && lstatSync(part).isSymbolicLink()) throw new Error('Refusing a symlink target: ' + part);
  }
  return dest;
}
function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const path = join(dir, e.name);
    if (e.isSymbolicLink()) throw new Error('Bundle contains a symlink: ' + path);
    return e.isDirectory() ? walk(path) : [path];
  });
}
function parseArgs(args) {
  const result = { apply: false, install: false, rollback: false };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (['--apply', '--install', '--rollback'].includes(a)) result[a.slice(2)] = true;
    else if (['--project', '--bundle'].includes(a)) {
      if (!args[i + 1] || args[i + 1].startsWith('--')) throw new Error('Missing value for ' + a);
      result[a.slice(2)] = args[++i];
    } else throw new Error('Unknown argument: ' + a);
  }
  if (!result.project) throw new Error('Usage: node migrate.mjs --project /path/to/clean-base-checkout [--apply --install | --rollback --apply]');
  if ((result.install || result.rollback) && !result.apply) throw new Error('--install/--rollback requires explicit --apply.');
  if (result.install && result.rollback) throw new Error('--install and --rollback are mutually exclusive.');
  return result;
}
function ensureRuntime() {
  const [major, minor] = process.versions.node.split('.').map(Number);
  if (major < 22 || (major === 22 && minor < 19)) throw new Error('Node >=22.19 is required for real dependency installation.');
}
export async function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv), project = realpathSync(resolve(args.project));
  if (args.bundle && realpathSync(resolve(args.bundle)) !== BUNDLE) throw new Error('--bundle must name this exact bundle.');
  const root = realpathSync(run('git', ['rev-parse', '--show-toplevel'], project).trim());
  if (root !== project) throw new Error('--project must be the repository root.');
  const gitdir = resolve(project, run('git', ['rev-parse', '--git-dir'], project).trim());
  const backup = join(gitdir, 'trisoul-migration-0.4.0');
  const recordPath = join(backup, 'record.json');
  if (args.rollback) {
    if (!existsSync(recordPath)) throw new Error('No migration record found.');
    const rec = JSON.parse(read(recordPath));
    // Check every owned path before restoring anything. Never overwrite newer work.
    for (const item of rec.files) {
      const dest = assertOwnedPath(project, item.path);
      const current = existsSync(dest) ? sha256(readFileSync(dest)) : null;
      if (current !== item.after) throw new Error('Post-migration changes detected; rollback refused: ' + item.path);
      if (item.before !== null && sha256(readFileSync(join(backup, item.backup))) !== item.before) throw new Error('Backup checksum mismatch: ' + item.path);
    }
    for (const item of rec.files) {
      const dest = assertOwnedPath(project, item.path);
      if (item.before === null) rmSync(dest, { force: true }); else atomic(dest, readFileSync(join(backup, item.backup)));
    }
    renameSync(recordPath, recordPath + '.rolled-back-' + Date.now());
    console.log('Source and recorded lockfile restored. Reinstall the restored lockfile before starting DSH; node_modules was not restored.');
    return;
  }
  if (args.install) ensureRuntime();
  if (existsSync(recordPath)) throw new Error('Migration already recorded. Roll back or reconcile; do not apply twice.');
  if (run('git', ['rev-parse', 'HEAD'], project).trim() !== META.base_commit) throw new Error('Unexpected base commit. Reconcile upstream changes first.');
  if (run('git', ['status', '--porcelain=v1', '--untracked-files=all'], project).trim()) throw new Error('The source tree has uncommitted work. Use a separate clean checkout.');
  const names = ['package.json','presets/trisoul-x/agent.cordis.yml','src/index.mjs','src/dsh-agent.mjs','src/state-zone.mjs'];
  const originals = Object.fromEntries(names.map(n => [n, read(assertOwnedPath(project, n))]));
  const edits = buildEdits(originals, JSON.parse(read(join(BUNDLE, 'state-wrapper-replacement.json'))));
  const runtimeFiles = ['cc-prompt-adapter.mjs','bindings.json',...walk(join(BUNDLE, 'prompts')).map(p => relative(BUNDLE,p))];
  for (const file of runtimeFiles) {
    const dest = 'src/cc-adaptation/' + file.replaceAll('\\','/');
    if (existsSync(assertOwnedPath(project,dest))) throw new Error('Existing adaptation file would be overwritten: ' + dest);
    edits.set(dest, read(join(BUNDLE,file)));
  }
  console.log('Target DSH: ' + META.dsh + ' (prerelease). Planned source files: ' + edits.size);
  for (const name of edits.keys()) console.log('  ' + name);
  if (!args.apply) { console.log('Dry run only. No files changed, packages installed or services restarted.'); return; }
  mkdirSync(backup, { recursive: true });
  const rec = { version:META.version, project, base:META.base_commit, createdAt:new Date().toISOString(), state:'applying', files:[] };
  for (const [path, content] of edits) {
    const dest=assertOwnedPath(project,path), before=existsSync(dest)?readFileSync(dest):null;
    const name=String(rec.files.length)+'.bin';
    if(before!==null)writeFileSync(join(backup,name),before,{mode:0o600});
    rec.files.push({path,backup:name,before:before===null?null:sha256(before),after:before===null?null:sha256(before),plannedAfter:sha256(content)});
  }
  // Track lockfile changes made by installation, including partial failures.
  if (args.install) {
    const path='pnpm-lock.yaml',dest=assertOwnedPath(project,path),before=existsSync(dest)?readFileSync(dest):null,name='lock.bin';
    if(before!==null)writeFileSync(join(backup,name),before,{mode:0o600});
    rec.files.push({path,backup:name,before:before===null?null:sha256(before),after:before===null?null:sha256(before)});
  }
  atomic(recordPath,JSON.stringify(rec,null,2));
  try {
    for (const [path,content] of edits) {
      atomic(assertOwnedPath(project,path),content);
      rec.files.find(f=>f.path===path).after=sha256(content);
      atomic(recordPath,JSON.stringify(rec,null,2));
    }
    rec.state='source-applied';atomic(recordPath,JSON.stringify(rec,null,2));
    if(args.install) {
      const pnpm=process.platform==='win32'?'pnpm.cmd':'pnpm';
      try {
        run(pnpm,['install','--no-frozen-lockfile'],project,'inherit');
        run(pnpm,['build'],project,'inherit');
        run(pnpm,['test'],project,'inherit');
        rec.state='build-and-tests-passed';
      } finally {
        const lock=rec.files.find(f=>f.path==='pnpm-lock.yaml'),path=join(project,'pnpm-lock.yaml');
        lock.after=existsSync(path)?sha256(readFileSync(path)):null;
      }
    }
  } catch(error) {
    rec.state='failed';rec.error=error.message;throw error;
  } finally { atomic(recordPath,JSON.stringify(rec,null,2)); }
  console.log('Migration source stage finished. No global DSH install, profile change, model request, or service restart was performed.');
}
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href===import.meta.url) {
  main().catch(error=>{console.error(error.message);process.exitCode=1;});
}
