import './build-host.mjs';
import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { whaleSvg } from '../src/client/brand.mjs';
import { packSkin } from './pack-skin.mjs';

await packSkin(fileURLToPath(new URL('../src/client/skins/google-material-expressive/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/google-material-expressive.json', import.meta.url)));

await packSkin(fileURLToPath(new URL('../src/client/skins/ios-liquid-glass/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/ios-liquid-glass.json', import.meta.url)));
await packSkin(fileURLToPath(new URL('../src/client/skins/codex-desktop/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/codex-desktop.json', import.meta.url)));

await packSkin(fileURLToPath(new URL('../src/client/skins/claude-cli-terminal/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/claude-cli-terminal.json', import.meta.url)));

// PTC shares the main composition and adds only its tool presentation.
const composition = await readFile(new URL('../presets/trisoul-x/agent.cordis.yml', import.meta.url), 'utf8');
await writeFile(new URL('../presets/omd-ptc/agent.cordis.yml', import.meta.url),
  '# Generated by scripts/build.mjs from trisoul-x/agent.cordis.yml.\n' + composition +
  "\n- id: tool-presentation\n  name: 'trisoul_x/ptc'\n");

await mkdir(new URL('../lib/', import.meta.url), { recursive: true });
for (const destination of ['../docs/images/logo.svg']) {
  const url = new URL(destination, import.meta.url);
  await mkdir(new URL('./', url), { recursive: true });
  await writeFile(url, whaleSvg('omd-logo').replace('aria-hidden="true"', 'role="img" aria-label="Oh My DSH"'));
}
await build({
  entryPoints: [fileURLToPath(new URL('../src/client/index.jsx', import.meta.url))],
  outfile: fileURLToPath(new URL('../lib/client.js', import.meta.url)),
  bundle: true, platform: 'browser', format: 'cjs', target: 'es2022',
  minifySyntax: true, minifyWhitespace: true, keepNames: true,
  external: ['react-dom', 'react', 'react/jsx-runtime', '@deepseek-ai/cordis', '@deepseek-ai/dsh-client-ui-primitives', '@deepseek-ai/dsh-api-session-controller/client'],
  banner: { js: 'window.__ModuleLoader__.load({id:"trisoul_x",factory:(require)=>{var module={exports:{}};var exports=module.exports;' },
  footer: { js: 'return module.exports;}});' },
  plugins: [{ name: 'inline-css', setup(b) {
    b.onLoad({ filter: /\.css$/ }, async args => ({ contents: `export default ${JSON.stringify(await readFile(args.path, 'utf8'))}`, loader: 'js' }));
  } }],
});
