import './build-host.mjs';
import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { whaleSvg } from '../src/client/brand.mjs';
import { packSkin } from './pack-skin.mjs';

await packSkin(fileURLToPath(new URL('../src/client/skins/google-material-expressive/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/google-material-expressive.json', import.meta.url)));

await packSkin(fileURLToPath(new URL('../src/client/skins/ios-liquid-glass/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/ios-liquid-glass.json', import.meta.url)));
await packSkin(fileURLToPath(new URL('../src/client/skins/codex-desktop/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/codex-desktop.json', import.meta.url)));

await packSkin(fileURLToPath(new URL('../src/client/skins/claude-cli-terminal/', import.meta.url)),
  fileURLToPath(new URL('../src/client/skins/bundled/claude-cli-terminal.json', import.meta.url)));

// The host mounts plugin-declared presets. Keep one authored composition;
// the PTC variant only adds its tool presentation.
const composition = await readFile(new URL('../presets/trisoul-x/agent.cordis.yml', import.meta.url), 'utf8');
const presets = [
  ['trisoul-x', 'Oh My DSH', '通用单模型 Agent，配备项目摘要、上下文替换、任务验证、电脑操控、技能与按需子代理。', composition],
  ['omd-ptc', 'omd-ptc', '完整 OMD 能力，通过 PTC 的 run_code 调用工具。', composition + "\n- id: tool-presentation\n  name: 'trisoul_x/ptc'\n"],
];
await writeFile(new URL('../presets/cordis.patch.yml', import.meta.url),
  '# Generated by scripts/build.mjs; edit trisoul-x/agent.cordis.yml.\n- insert:\n' +
  presets.map(([id, name, description, plugins], order) => `    - id: preset-${id}\n      name: '@deepseek-ai/dsh-agent-preset'\n      config:\n        id: ${id}\n        name: ${JSON.stringify(name)}\n        description: ${JSON.stringify(description)}\n        order: ${order}\n        plugins:\n${plugins.trimEnd().split('\n').map(line => '          ' + line).join('\n')}\n`).join(''));

await mkdir(new URL('../lib/', import.meta.url), { recursive: true });
for (const destination of ['../docs/images/logo.svg']) {
  const url = new URL(destination, import.meta.url);
  await mkdir(new URL('./', url), { recursive: true });
  await writeFile(url, whaleSvg('omd-logo').replace('aria-hidden="true"', 'role="img" aria-label="Oh My DSH"'));
}
await build({
  entryPoints: [fileURLToPath(new URL('../src/client/index.jsx', import.meta.url))],
  outfile: fileURLToPath(new URL('../lib/client.js', import.meta.url)),
  bundle: true, platform: 'browser', format: 'cjs', target: 'es2022',
  minifySyntax: true, minifyWhitespace: true, keepNames: true,
  external: ['react-dom', 'react', 'react/jsx-runtime', '@deepseek-ai/cordis', '@deepseek-ai/dsh-client-ui-primitives', '@deepseek-ai/dsh-api-session-controller/client'],
  banner: { js: 'window.__ModuleLoader__.load({id:"trisoul_x",factory:(require)=>{var module={exports:{}};var exports=module.exports;' },
  footer: { js: 'return module.exports;}});' },
  plugins: [{ name: 'inline-css', setup(b) {
    b.onLoad({ filter: /\.css$/ }, async args => ({ contents: `export default ${JSON.stringify(await readFile(args.path, 'utf8'))}`, loader: 'js' }));
  } }],
});
